apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}--cantaloupe
  labels:
    {{- include "articleHosting.labels" . | nindent 4 }}
    app.kubernetes.io/component: cantaloupe
spec:
  type: LoadBalancer
  ports:
    - targetPort: http
      port: 80
      protocol: TCP
      name: http
    - targetPort: http
      port: 443
      name: https
  selector:
      {{- include "articleHosting.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: cantaloupe
